FROM gcr.io/cloud-solutions-images/jenkins-k8s-slave

RUN 	apt-get update && \
	curl -sL https://deb.nodesource.com/setup_8.x | bash - && \
	apt-get install -y nodejs && \
	apt-get install -y build-essential && \
	apt-get install -y zip


